config/routes.rb
Rails.application.routes.draw do

  resources :articles do
    resources :comments, only: [:create, :destroy]
    put 'publish', on: :member
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories

  root 'articles#index'

  match '/login', to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'

  get '/search', to: 'search#search', as: 'search'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  validates :name, presence: true
  validates :text, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login, except: :create
  
  def create
    @article = Article.find(params[:article_id])
    comment = @article.comments.create(comment_params)
    if comment.invalid?
      flash[:error] ||= []
      flash[:error] << "Name can't be blank" if comment.name.blank?
      flash[:error] << "Comment can't be blank" if comment.text.blank?
    end
    redirect_to @article
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to article_path(params[:article_id])
  end
  
  private

  def comment_params
    params.require(:comment).permit(:name, :text)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <% if signed_in? %>
	    <%= link_to article_comment_path(comment.article.id, comment.id),
        method: :delete, data: { confirm: 'Are you sure?' } do %>
        <div class="btn btn-danger delete-comment">Delete</div>
      <% end %>
    <% end %>
    <h4 class="name"><%= comment.name %></h4>
	  <%= time_tag comment.created_at, format: '%e %B %Y ~ %H:%M' %>
  </div>
  <div class="panel-body">
    <%= comment.text %>
  </div>
</div>

app/views/comments/_comment_form.html.erb
<%= form_for [@article, @comment], html: { role: 'form' } do |f| %>
	<div class="form-group">
		<%= f.label 'Name', class: 'control-label' %>
		<%= f.text_field :name, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label 'Comment', class: 'control-label' %>
		<%= f.text_area :text, rows: 5, class: 'form-control' %>
	</div>
	<%= f.submit 'Add Comment', class: 'btn btn-default' %>
<% end %>