config/routes.rb
Rails.application.routes.draw do

  resources :articles do
    resources :comments, only: [:create, :destroy]
    put 'publish', on: :member
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories

  root 'articles#index'

  match '/login', to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'

  get '/search', to: 'search#search', as: 'search'

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true
  validates :text, presence: true
  has_many :comments
  has_and_belongs_to_many :categories

  enum status: [:draft, :published]

  default_scope { order('created_at DESC') }

  def self.containing_string(search_string)
    where("title LIKE ? OR text LIKE ?",
          "%#{search_string}%", "%#{search_string}%")
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_login, except: [:index, :show]
  
  def index
    if signed_in?
      articles = Article.all
    else
      articles = Article.published
    end
    @articles = articles.page(params[:page]).per(5)
  end

  def new
    @article = Article.new
  end

  def create
    if params[:article][:categories]
      categories = Category.find(params[:article][:categories].reject(&:empty?))
    else
      categories = []
    end

    @article = Article.new(article_params.merge({ categories: categories }))
    
    if @article.save
      flash[:success] = "Article created"
      redirect_to @article
    else
      flash.now[:error] ||= []
      if @article.title.blank?
        flash.now[:error] << "Title can't be blank"
      end
      if @article.text.blank?
        flash.now[:error] << "Text can't be blank"
      end
      render :new
    end
  end

  def show
    @article = Article.find(params[:id])
    redirect_to root_path if @article.draft? and !signed_in?
    @comment = Comment.new(name: 'Guest')
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if params[:article][:categories]
      categories = Category.find(params[:article][:categories].reject(&:empty?))
    else
      categories = @article.categories
    end

    if @article.update_attributes(article_params.merge({ categories: categories}))
      flash[:success] = 'Article updated'
      redirect_to @article
    else
      flash.now[:error] ||= []
      if @article.title.blank?
        flash.now[:error] << "Title can't be blank"
      end
      if @article.text.blank?
        flash.now[:error] << "Text can't be blank"
      end
      render :edit
    end
  end

  def destroy
    Article.delete params[:id]
    redirect_to articles_path, flash: { success: 'Article deleted' }
  end

  def publish
    article = Article.find params[:id]
    if article.published?
      article.draft!
    else
      article.published!
    end
    redirect_to :back
  end

  private

  def article_params
    params.require(:article).permit(:title, :text, :status)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def admin_button(article)
    if article.published?
      link_text = 'Unpublish'
      button_style = 'btn-success'
    else
      link_text = 'Publish'
      button_style = 'btn-danger'
    end
    render partial: 'articles/admin_button', locals: {
      article: article,
      link_text: link_text,
      button_style: button_style
    }
  end
end

app/views/articles/_admin_button.html.erb
<div class="btn-group admin-dropdown">
  <%= link_to link_text, publish_article_path(article), method: :put, class: "btn btn-sm #{button_style}", type: "button" %>
	<button type="button" class="btn btn-sm <%= button_style %> dropdown-toggle" data-toggle="dropdown">
    <span class="caret"></span>
		<span class="sr-only">Toggle Dropdown</span>
  </button>
	<ul class="dropdown-menu" role="menu">
		<li><%= link_to 'Edit article', edit_article_path(article) %></li>
		<li><%= link_to 'Delete article', article, method: :delete,
    data: { confirm: 'Are you sure?' } %></li>
	</ul>
</div>

app/views/articles/_article.html.erb
<article>
  <% if signed_in? %>
		<%= admin_button(article) %>
	<% end %>
	<h1><%= link_to article.title, article_path(article) %></h1>
	<p><%= time_tag article.created_at, format: '%e %B %Y' %></p>
  <p>
	  <% article.categories.each do |category| %>
		  <%= link_to category_path(category), class: 'category-label' do %>
        <span class="label label-default"><%= category.name %></span>
      <% end %>
	  <% end %>
  </p>
	<%= simple_format article.text %>
</article>
<div class="comment-count">
  <% if local_assigns.has_key? :comment_count %>
    <%= link_to "- #{article.comments.size} comments -", article_path(article) %>
  <% end %>
</div>

app/views/articles/_article_divider.html.erb
<hr class="divider">

app/views/articles/_article_form.html.erb
<%= form_for @article, html: { role: 'form' } do |f| %>
	<div class="form-group">
		<%= f.label :title, class: 'control-label' %>
		<%= f.text_field :title, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :text, class: 'control-label' %>
		<%= f.text_area :text, rows: 10, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :categories, class: 'control-label' %>
		<%= collection_select(:article, :categories, Category.all, :id, :name,
													{ selected: @article.categories.map(&:id) },
													multiple: true, class: 'form-control') %>
	</div>
	<div class="form-group">
		<div class="radio-inline">
			<%= f.radio_button :status, :draft %>
			<%= f.label :status, 'Draft', value: :draft %>
		</div>
		<div class="radio-inline">
			<%= f.radio_button :status, :published %>
			<%= f.label :status, 'Published', value: :published %>
		</div>
	</div>
	
	<%= f.submit submit_text, class: 'btn btn-default' %>
	<%= link_to 'Cancel', :back, class: 'cancel-link' %>
<% end %>

app/views/articles/edit.html.erb
<% content_for :title, 'Edit Article' %>
<h1>Edit article</h1>
<%= render 'article_form', submit_text: 'Update' %>

app/views/articles/index.html.erb
<% content_for :title, 'Articles' %>
<%= render partial: @articles, locals: { comment_count: true },
  spacer_template: 'article_divider' %>
<br><br>
<div class="text-center">
	<%= paginate @articles %>
</div>

app/views/articles/new.html.erb
<% content_for :title, 'New Article' %>
<h1>Create a new article</h1>
<%= render 'article_form', submit_text: 'Create' %>

app/views/articles/show.html.erb
<% content_for :title, @article.title %>
<%= render @article %>
<hr class="divider">
<section>
	<h2 id="comments">Comments</h2>
	<br>
	<%= render @article.comments %>
	<br>
	<%= render 'comments/comment_form' %>
</section>