config/routes.rb
Rails.application.routes.draw do

  resources :articles do
    resources :comments, only: [:create, :destroy]
    put 'publish', on: :member
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories

  root 'articles#index'

  match '/login', to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'

  get '/search', to: 'search#search', as: 'search'

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true
  validates :name, uniqueness: true
  has_and_belongs_to_many :articles

  scope :sort_alphabetically, -> { order(name: :asc) }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_login, except: [:index, :show]
  
  def index
    @categories = Category.all.sort_alphabetically
  end

  def show
    @category = Category.find(params[:id])
    if signed_in?
      articles = @category.articles
    else
      articles = @category.articles.published
    end
    @articles = articles.page(params[:page]).per(5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      flash.now[:error] ||= []
      if @category.name.blank?
        flash.now[:error] << 'Name cannot be blank'
      elsif
        flash.now[:error] << 'Category already exists'
      end
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      redirect_to categories_path
    else
      flash.now[:error] ||= []
      @category.errors.each do |attribute|
        @category.errors[attribute].each do |error| 
          flash.now[:error] << "#{attribute.capitalize} #{error}"
        end
      end

      render :edit
    end
  end

  def destroy
    Category.destroy(params[:id])
    flash[:notice] = 'Category deleted'
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<%= link_to category, class: 'list-group-item' do %>
	<%= category.name %>
	<span class="badge"><%= category.articles.published.size %></span>
<% end %>
<% if signed_in? %>
	(<%= link_to 'Edit', edit_category_path(category) %> |
	<%= link_to 'Delete', category_path(category), method: :delete %>)
<% end %>

app/views/categories/_category_form.html.erb
<%= form_for @category, html: { role: 'form' } do |f| %>
	<div class="form-group">
		<%= f.label :name, class: 'control-label' %>
		<%= f.text_field :name, class: 'form-control' %>
	</div>
	<%= f.submit nil, class: 'btn btn-default' %>
	<%= link_to 'Cancel', :back, class: 'cancel-link'  %>
<% end %>

app/views/categories/edit.html.erb
<% content_for :title, 'Edit category' %>
<h1>Edit category</h1>
<%= render 'category_form' %>

app/views/categories/index.html.erb
<% content_for :title, 'Categories' %>
<h1>Categories</h1>
<div class="list-group">
	<%= render @categories %>
</div>

app/views/categories/new.html.erb
<% content_for :title, 'New Category' %>
<h1>Create a new category</h1>
<%= render 'category_form' %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<%= render partial: @articles, spacer_template: 'articles/article_divider' %>
<div class="text-center">
  <%= paginate @articles %>
</div>