config/routes.rb
Rails.application.routes.draw do

  resources :articles do
    resources :comments, only: [:create, :destroy]
    put 'publish', on: :member
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories

  root 'articles#index'

  match '/login', to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'

  get '/search', to: 'search#search', as: 'search'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  private
  
  def require_login
    unless signed_in?
      flash[:error] = 'You must be logged in to do that'
      redirect_to login_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when 'notice' then 'alert alert-info'
    when 'success' then 'alert alert-success'
    when 'error' then 'alert alert-danger'
    when 'alert' then 'alert alert-warning'
    end
  end

  def current?(path)
    'active' if current_page? path
  end
end

app/views/application/_admin_menu.html.erb
<nav>
  <h2>Admin</h2>
  <ul>
	  <%= link_to new_article_path do %>
      <li class="<%= current?(new_article_path) %>">New Article</li>
    <% end %>
	  <%= link_to new_category_path do %>
      <li class="<%= current?(new_category_path) %>">New Category</li>
    <% end %>
  </ul>
</nav>

app/views/application/_categories_menu.html.erb
<nav id='categories-menu'>
	<h2>Categories</h2>
	<ul>
		<% Category.all.sort_alphabetically.each do |category| %>
      <%= link_to category_path(category) do %>
			  <li class="<%= current?(category_path(category)) %>">
          <%= category.name %>
        </li>
      <% end %>
		<% end %>
	</ul>
</nav>

app/views/application/_header.html.erb
<header>

</header>

app/views/application/_messages.html.erb
<% flash.each do |key, value| %>
	<div class="<%= flash_class(key) %>">
		<ul>
			<% if value.respond_to?(:each) %>
				<% value.each do |value| %>
					<li><%= value %></li>
				<% end %>
			<% else %>
				<li><%= value %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-inverse" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse"
							data-target="#navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to root_path, class: 'navbar-brand' do %>
				<span class="glyphicon glyphicon-home"></span>
			<% end %>
		</div>

		<div class="collapse navbar-collapse" id="navbar-collapse">
			<ul class="nav navbar-nav">
        <li class="<%= current?(categories_path) %>">
          <%= link_to 'Categories', categories_path %>
        </li>
        <li class="<%= current?(search_path) %>">
          <%= link_to 'Search', search_path %>
        </li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li class="<%= current?(login_path) %>">
					<% if signed_in? %>
						<%= link_to 'Log out', logout_path, method: :delete %>
					<% else %>
						<%= link_to 'Log in', login_path %>
					<% end %>
				</li>
			</ul>
		</div>
	</div>
</nav>

app/views/application/_notices.html.erb
<% flash.each do |key, value| %>
	<div class="<%= flash_class(key) %>">
		<ul>
			<% if value.respond_to?(:each) %>
				<% value.each do |value| %>
					<li><%= value %></li>
				<% end %>
			<% else %>
				<li><%= value %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/application/_search_bar.html.erb
<h2>Search</h2>
<%= render 'search/search_form' %>